# Generated by Django 5.1.7 on 2025-03-09 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Job_opening', '0003_applicantresponse_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.JSONField(default=list)),
                ('status', models.CharField(default='In Progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_job_pipeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Job_opening.applicantresponse')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbal_scores', models.JSONField()),
                ('non_verbal_scores', models.JSONField()),
                ('final_report', models.TextField()),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='call.interview')),
            ],
        ),
    ]
