# Generated by Django 5.1.7 on 2025-03-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresult',
            name='non_verbal_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='verbal_scores',
            field=models.JSONField(default=dict),
        ),
    ]
