# Generated by Django 5.1.7 on 2025-03-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_alter_evaluationresult_non_verbal_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationresult',
            name='final_report',
            field=models.JSONField(default=dict),
        ),
    ]
