# Generated by Django 5.1.7 on 2025-03-09 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('applicants', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Archived', 'Archived')], default='Pending', max_length=20)),
                ('postedDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('jobType', models.CharField(blank=True, max_length=20, null=True)),
                ('experienceLevel', models.CharField(blank=True, max_length=20, null=True)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('application_link', models.URLField(blank=True, max_length=255, null=True)),
                ('benchmark', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_auth.company')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicantId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('appliedFor', models.CharField(max_length=255)),
                ('appliedDate', models.DateField()),
                ('cvKeywords', models.JSONField(blank=True, null=True)),
                ('resumeParseData', models.JSONField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Job_opening.jobopening')),
            ],
        ),
    ]
