# Generated by Django 5.1.7 on 2025-03-09 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='postedDate',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 3, 9, 17, 42, 33, 897066)),
            preserve_default=False,
        ),
    ]
