# Generated by Django 5.1.6 on 2025-03-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0002_jobopening_application_link_jobopening_benchmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresponse',
            name='email',
            field=models.EmailField(default='lamsalranjan19@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
