# Generated by Django 5.1.6 on 2025-03-04 14:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0002_alter_jobopening_company_delete_company'),
        ('client_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 4, 14, 52, 4, 414200)),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ArchivedJobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('form_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_auth.company')),
            ],
        ),
    ]
