# Generated by Django 5.1.7 on 2025-03-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0003_applicantresponse_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
