# Generated by Django 5.1.6 on 2025-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0003_jobopening_deadline_archivedjobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresponse',
            name='country',
            field=models.CharField(default='Nepal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantresponse',
            name='email_address',
            field=models.EmailField(default='None@none.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantresponse',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantresponse',
            name='name',
            field=models.CharField(default='John Doe', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantresponse',
            name='phone_number',
            field=models.CharField(default='9800000000', max_length=20),
            preserve_default=False,
        ),
    ]
