# Generated by Django 5.1.6 on 2025-03-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0004_applicantresponse_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
