# Generated by Django 5.1.7 on 2025-03-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0004_alter_applicantresponse_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='experienceLevel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='jobType',
            field=models.CharField(blank=True, null=True),
        ),
    ]
