# Generated by Django 5.1.6 on 2025-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0005_alter_applicantresponse_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresponse',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
