# Generated by Django 5.1.6 on 2025-03-07 13:52

import Job_opening.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0006_applicantresponse_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=Job_opening.models.cv_upload_path),
        ),
    ]
