# Generated by Django 5.1.6 on 2025-03-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_opening', '0007_alter_applicantresponse_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantresponse',
            name='cv_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
